import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";
import localFont from 'next/font/local'


const poppins = Poppins({
  weight: ["100", "400", "500", "600", "800"]
});

export const fontBangla = localFont({
  src: "../fonts/bangla.ttf",
  // weight: ["100", "400", "500", "600", "800"]
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className}  antialiased`}
      >
        <header>
          <Navbar></Navbar>
        </header>
        <main className="min-h-[calc(100vh-302px)]">
          {children}
        </main>
        <Footer></Footer>
      </body>
    </html>
  );
}
